 Exercise 1 : Array Creation And Manipulation
Create a 1D NumPy array containing numbers from 0 to 9.

In [1]:
import numpy as np
array = np.arange(0, 10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

 Exercise 2 : Type Conversion And Array Operations
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

In [2]:
arr = np.array([3.14, 2.17, 0, 1, 2], dtype=int)
arr

array([3, 2, 0, 1, 2])

Exercise 3 : Working With Multi-Dimensional Arrays
Create a 3x3 NumPy array with values ranging from 1 to 9.

In [5]:
arr = np.random.randint(1, 10, size=(3,3))
print(arr)

[[5 8 9]
 [7 2 3]
 [9 5 6]]


Exercise 4 : Creating Multi-Dimensional Array With Random Numbers
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

In [12]:
arr = np.round(np.random.rand(4, 5),2)
arr

array([[0.39, 0.09, 0.09, 0.48, 0.4 ],
       [0.88, 0.51, 0.36, 0.55, 0.81],
       [0.14, 0.77, 0.11, 0.37, 0.94],
       [0.28, 0.68, 0.38, 0.46, 0.93]])

 Exercise 5 : Indexing Arrays
Select the second row from a given 2D NumPy array.

In [18]:
second_row =  arr[1, :]
second_row

array([0.88, 0.51, 0.36, 0.55, 0.81])

 Exercise 6 : Reversing Elements
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [19]:
reversed_array = second_row[::-1]
reversed_array

array([0.81, 0.55, 0.36, 0.51, 0.88])

Exercise 7 : Identity Matrix
Create a 4x4 identity matrix using NumPy.

In [23]:
identity_matrix = np.identity(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

 Exercise 8 : Simple Aggregate Funcs
Find the sum and average of a given 1D array.

In [72]:
arr = np.random.randint(1, 10, 3)
print(arr)
sum_values = np.sum(arr)
print('sum = ', sum_values)
avg_values = np.round(np.average(arr),2)
print('avg_values = ', avg_values)

[2 2 4]
sum =  8
avg_values =  2.67


 Exercise 9 : Create Array And Change Its Structure
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

In [73]:
arr = np.arange(1, 21)
matrix = arr.reshape(4, 5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Exercise 10 : Conditional Selection Of Values
Extract all odd numbers from a given NumPy array.

In [100]:
arr = np.random.randint(1, 100, 5)
odd_numbers = arr[arr % 2 != 0]
print(arr)
print('odd_numbers: ', odd_numbers)

[47 17  6 62 96]
odd_numbers:  [47 17]
